[package]
name = "project-tracker-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
project-tracker-core = { path = "../domain" }
ratatui = "0.28"
crossterm = "0.28"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
